# Generated by Django 2.1.5 on 2019-02-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Blogs Image'),
        ),
    ]
