# Generated by Django 2.0.13 on 2019-02-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20190224_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('1', 'Publish'), ('0', 'Unpublished')], max_length=1, null=True),
        ),
    ]
