# Generated by Django 2.0.13 on 2019-02-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20190222_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='views',
            field=models.CharField(blank=True, default=0, max_length=5000, null=True),
        ),
    ]
