# Generated by Django 2.0.13 on 2019-02-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20190224_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked',
            field=models.CharField(choices=[('1', 'Checked'), ('0', 'Unchecked')], default='0', max_length=1),
        ),
    ]
