# Generated by Django 2.0.13 on 2019-02-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Doctor Image'),
        ),
    ]
