# Generated by Django 2.0.13 on 2019-02-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_booking_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='next',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='treatment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
