# Generated by Django 2.0.13 on 2019-02-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20190222_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=500)),
                ('fn', models.CharField(max_length=100)),
                ('ln', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(max_length=800)),
                ('location', models.CharField(max_length=300)),
                ('street1', models.CharField(max_length=200)),
                ('street2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal', models.CharField(blank=True, max_length=100, null=True)),
                ('confirm', models.CharField(choices=[('1', 'Confirmed'), ('0', 'Unconfirmed')], default='0', max_length=1)),
                ('doctor', models.ManyToManyField(to='doctor.Doctor')),
            ],
        ),
    ]
