# Generated by Django 2.0.13 on 2019-02-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='counter',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
    ]
