# Generated by Django 2.0.13 on 2019-02-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_type_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('rev', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('1', 'Publish'), ('0', 'Unpublished')], default=0, max_length=1, null=True)),
                ('image', models.FileField(upload_to='', verbose_name='User Image')),
            ],
        ),
    ]
