# Generated by Django 2.0.13 on 2019-02-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='doctor',
            field=models.ManyToManyField(to='doctor.Doctor'),
        ),
    ]
