# Generated by Django 2.0.13 on 2019-02-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_review_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
