# Generated by Django 2.0.13 on 2019-02-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_remove_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
