# Generated by Django 2.1.5 on 2019-02-15 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=100, verbose_name='First Name')),
                ('ln', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=500, verbose_name='Phone number')),
                ('image', models.ImageField(upload_to='img/user', verbose_name='User Image')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('username', models.CharField(max_length=250, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=500, verbose_name='Password')),
                ('email', models.CharField(max_length=250, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=0, verbose_name='Status')),
                ('soft', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=0)),
                ('soft', models.BooleanField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='role',
            field=models.ManyToManyField(to='players.Role', verbose_name='Role'),
        ),
    ]
