# Generated by Django 2.1.5 on 2019-02-08 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=0)),
                ('soft', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('fn', models.CharField(max_length=100)),
                ('ln', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=500)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Role')),
                ('image', models.ImageField(upload_to='img/user')),
                ('address', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=0)),
                ('soft', models.BooleanField(default=1)),
            ],
        ),
    ]
