# Generated by Django 2.1.5 on 2019-02-16 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('phone1', models.CharField(max_length=500, null=True)),
                ('phone2', models.CharField(max_length=500, null=True)),
                ('email', models.CharField(max_length=1000, null=True)),
                ('facebook', models.CharField(max_length=500, null=True)),
                ('instagram', models.CharField(max_length=500, null=True)),
                ('twitter', models.CharField(max_length=500, null=True)),
                ('youtube', models.CharField(max_length=500, null=True)),
                ('fax', models.CharField(max_length=1000, null=True)),
                ('pobox', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
