# Generated by Django 2.1.5 on 2019-02-15 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('found', models.CharField(choices=[('i', 'Inside KTM Valley'), ('o', 'Outside KTM Valley'), ('w', 'Whole Nepal')], max_length=1, null=True)),
                ('summary', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=0)),
                ('doctor', models.ManyToManyField(to='doctor.Doctor')),
            ],
        ),
    ]
