# Generated by Django 2.1.5 on 2019-02-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='doctor',
            field=models.ManyToManyField(to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='found',
            field=models.CharField(choices=[('i', 'Inside KTM Valley'), ('o', 'Outside KTM Valley'), ('w', 'Whole Nepal')], max_length=1, null=True),
        ),
    ]
