# Generated by Django 2.1.5 on 2019-02-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_auto_20190216_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='status',
            field=models.CharField(choices=[('1', 'Publish'), ('0', 'Unpublished')], max_length=1, null=True),
        ),
    ]
