# Generated by Django 2.1.5 on 2019-02-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_auto_20190216_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='level',
            field=models.CharField(choices=[('1', 'Dangerouse'), ('2', 'Mid Range'), ('0', 'Normal')], max_length=1, null=True),
        ),
    ]
